### ISSUE TITLE
remove ( powered by humhub ) from login/signup form and email layout

### ISSUE THREAD

**Issue by ghost** [GreenVolume/humhub-discordblue-theme#1]
i changed ( theme/humhub ) to ( theme/my file) and the theme work fine , but i want to remove powered by humhub from login/signup form and email layout so how i can do it ?

**Comment by Felli** [comment]
# Email
For email layout copy the whole  mail folder from [`/protected/humhub/views/mail`](https://github.com/humhub/humhub/tree/master/protected/humhub/views/mail) and on [line 697](https://github.com/humhub/humhub/blob/master/protected/humhub/views/mail/layouts/html.php#L697) remove what you're looking for (Note : You'll have to remove it from [line 10](https://github.com/humhub/humhub/blob/master/protected/humhub/views/mail/layouts/text.php#L10) in `text.php` as well) Once you done this please move the whole folder into `/YOUR-HUMHUB/themes/YOURTHEME/views`

## Custom Email Colors
For custom coloring please read my wiki [here](https://github.com/GreenVolume/humhub-discordblue-theme/wiki/Custom-Email-Colors)

# Login/Sign Up
For this you do the same thing you did above, copy [`/protected/humhub/modules/user/views/layouts`](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/layouts/main.php) (The whole folder!) edit and remove [line 27](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/layouts/main.php#L27), once that is done place the whole user folder into `/YOUR-HUMHUB/themes/YOURTHEME/views`

> Edit: For those wishing to do the same thing I've opened a new wiki [here](https://github.com/GreenVolume/humhub-discordblue-theme/wiki/Removing-%22Powered-by%22)

**Comment by ghost** [comment]
well , i removed it from email and it's working  , but i still unable to remove it form login/signup form , i placed the whole (user file)  on (  /public_html/MY-HUMHUB/themes/MYTHEME/views ) and removed the line 27 , but nothing changed
![communityissue](https://user-images.githubusercontent.com/25205782/28945798-d9c77b48-785c-11e7-890d-8876a89865bd.PNG)

**Comment by Felli** [comment]
Please go into your site's `ACP --> Settings ---> Advanced` and clear cache and view it again.

**Comment by Felli** [comment]
# Both folders are needed here in `user`
![](https://image.prntscr.com/image/yl-v2LHQT5_FIylvEq_4vw.png)

# Layout Folder
![](https://image.prntscr.com/image/d8ZC33UxTE6wo0yHJLmd9A.png)

# Registration Folder
![](https://image.prntscr.com/image/s4YrCYD7S4Gv_5IXgYNp0g.png)

**Comment by grawlfang** [comment]
I removed the powered by line on the signup/login page by editing the protected/config/common.php file and adding the following to it:

return [
  'params' => [
    'hidePoweredBy' => true
  ]
];

In theory this should remove it from anywhere that the powered by line exists.

See [humhub documentation](http://docs.humhub.org/admin-advanced-configuration.html) for general details
